import { v2Colors } from "./colors";

export const v2LegacyDarkTheme = {
  accent: v2Colors.accentPrimary,
  accentSoft: v2Colors.surfacePressed,
  background: v2Colors.background,
  badgeBackground: v2Colors.surfaceElevated,
  badgeText: v2Colors.textPrimary,
  border: v2Colors.borderDefault,
  card: v2Colors.surface,
  danger: v2Colors.danger,
  dangerSoft: "rgba(199, 165, 165, 0.14)",
  dotEmpty: v2Colors.borderStrong,
  habitCardBorder: v2Colors.borderDefault,
  habitCardCompletedBorder: v2Colors.accentPrimary,
  heroBadge: "rgba(243, 243, 243, 0.10)",
  heroMuted: v2Colors.textSecondary,
  heroSoftText: v2Colors.textPrimary,
  input: v2Colors.surface,
  inputBackground: v2Colors.backgroundElevated,
  inverseText: v2Colors.accentContrast,
  modalBackdrop: v2Colors.overlay,
  muted: v2Colors.textSecondary,
  primary: v2Colors.accentPrimary,
  primaryDark: v2Colors.textSecondary,
  primarySoft: v2Colors.surfacePressed,
  shadow: "#000000",
  softText: v2Colors.textMuted,
  success: v2Colors.success,
  successSoft: "rgba(191, 200, 191, 0.14)",
  surface: v2Colors.backgroundElevated,
  swatchBorder: v2Colors.borderDefault,
  text: v2Colors.textPrimary,
  warning: v2Colors.warning,
};
